-- Run this script in your Supabase SQL Editor
-- This is a foolproof method to grant Admin privileges. 
-- It looks up your EXACT UUID generated by Google Sign-In via your email address
-- and forces a profile creation or update with that identity!

DO $$
DECLARE
  target_user_id uuid;
BEGIN
  -- 1. Find your exact user ID from the secure auth.users table using your email
  SELECT id INTO target_user_id 
  FROM auth.users 
  WHERE email = 'j.parganiha@gmail.com' 
  LIMIT 1;

  IF target_user_id IS NOT NULL THEN
    -- 2. Force an UPSERT into public.profiles with that exact ID
    INSERT INTO public.profiles (id, role, status)
    VALUES (target_user_id, 'Admin', 'active')
    ON CONFLICT (id) DO UPDATE 
    SET 
      role = 'Admin', 
      status = 'active';

    RAISE NOTICE 'Successfully granted Admin to User ID: %', target_user_id;
  ELSE
    RAISE EXCEPTION 'Could not find a user with the email j.parganiha@gmail.com in auth.users';
  END IF;
END $$;
